# Generated by Django 2.1 on 2019-05-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20190508_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sq_fit',
            field=models.IntegerField(),
        ),
    ]
