# Generated by Django 2.1 on 2019-05-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='descripton',
            new_name='description',
        ),
    ]
